<a href="https://colab.research.google.com/github/magrosskopf/EA4/blob/main/DataSience_EA4_1%2B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print("numpy version: ")
print(np.__version__)

array = np.arange(12)
print("array with 12 Elements: ")
print(array)

array = np.where(array % 2 == 0, -1, array)
print("array where even numbers (and zero) are replaced by -1: ")
print(array)


array = array.reshape(4, -1)

print("array reshaped to 4 rows: ")
print(array)

bool_array = np.full((5, 3), True, dtype=bool)
print("array of 5x3 true: ")
print(bool_array)

numpy version: 
1.19.5
array with 12 Elements: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
array where even numbers (and zero) are replaced by -1: 
[-1  1 -1  3 -1  5 -1  7 -1  9 -1 11]
array reshaped to 4 rows: 
[[-1  1 -1]
 [ 3 -1  5]
 [-1  7 -1]
 [ 9 -1 11]]
array of 5x3 true: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
